population_size = 2000
trials_per_program = 10
tournament_size = 5
reproduce_weight = 10
mutate_weight = 20
crossover_weight = 70
tree_depth = 6

[start_position.y]
min = 300.0
max = 300.0

[start_position.x]
min = 0.0
max = 0.0

[start_position.o]
min = -1.60
max = 1.60
