population_size = 1000
trials_per_program = 10
tournament_size = 10
reproduce_weight = 10
mutate_weight = 20
crossover_weight = 70

[start_position.y]
min = 400.0
max = 600.0

[start_position.x]
min = 0.0
max = 0.0

[start_position.o]
min = -3.14
max = 3.14
